### ISSUE TITLE
waterdepth in ibScour

### ISSUE THREAD

**Issue by michinegro** [psu-efd/ibScourFoam#3]
Hello! I’ve been trying to modify the sediment transport module of ibScourFoam.  I'd like to obtain values of water depth to make calculations of sediment transport inside the sedModules. I’m a little confused about how to calculate waterdepths. I noticed that a variable waterDepth is used to calculate utau in the immerseBoundaryFvMeshUpdateCellValues.C and also in the wallFuncModules.C file to calculate H. I was wondering how to access to waterdepths values  or if not possible, how to calculate waterdepths inside the sedModules files. Should I create a new variable or is it possible to access to the value of waterDepth?
Any help is greatly appreciated.

**Comment by Yalan-Song** [comment]
Hi! In our work, we assumed the top boundary condition is a rigid lid.  The water depth won't change during the simulation. The water depth can be read from the constant/immersedBoundaryProperties.
We did not use the function: initialIB and setInlet in file immerseBoundaryFvMeshUpdateCellValues.C any more.  Instead, the inlet boundary uses the timeVaryingMappedFixedValue boundary condition, which will read the inlet profile from the constant/boundaryData. Please let me know if you have more questions.

**Comment by michinegro** [comment]
Thank you! This really helped me a lot. I have two questions regarding this. I was checking the boundary condition for pressure at the top is set as a zero gradient. My first question is: why did you decided that condition and how this condition affect the hydrostatic pressure?
My second question is regarding the cause of flow. I'm really sorry to ask this basic question but usually the flow is caused by the gravity (due to some slope). In this case, the bed slope is flat (0 degrees) so I was wondering what is the reason for the flow to move from the inlet to the outlet.
Thank you for your help!

**Comment by Yalan-Song** [comment]
You first question is a very interesting topic. Usually, if the water depth is deep enough, the effect of the free surface is very small to the wall shear stress on the bed that is driving force of scour. We think it is reasonable to view the water surface as a rigid lid. I found two papers may help you to understand this problem. (Free-Surface versus Rigid-Lid LES Computations for Bridge-Abutment Flow, Numerical Investigation of the Influence of Water Jumping on the Local Scour beneath a Pipeline under Steady Flow).
For your second question, the hydrostatic pressure effects are cancelled out by the gravity term in the source code of OpenFoam(https://www.openfoam.com/documentation/guides/latest/doc/guide-applications-solvers-variable-transform-p-rgh.html). The flow is not driven by the gravity but the pressure gradient. Here is a link about how to set boundary conditions of inlet and outlet. https://www.simscale.com/docs/simulation-setup/boundary-conditions/velocity-inlet-and-velocity-outlet/

**Comment by michinegro** [comment]
Thank you very much for your reply! I understand much better the conditions. I just have a few more questions. As the flow is caused by the pressure gradient and for the inlet the condition for pressure is set to zeroGradient, that means that the flow is not moving at the inlet. Did I understand that correctly? I think I'm missing something a this point, as that is not possible.
I also noticed that a velocity profile is set in the inlet with the timeVaryingMappedFixedValue  but would it be possible to set discharge instead?
I really appreciate the time you are taking to reply my questions.

**Comment by psu-efd** [comment]
These are all good questions. At any boundary, if you fix the velocity value, you usually need to set the pressure gradient to be zero. On the other hand, if you fixed the value of pressure, you need to set the velocity gradient. The system will figure out what the needed mean pressure gradient to drive the flow. There are other ways to drive the flow in the channel. I suggest you have a look at some CFD textbooks. Thanks for your interest.

**Comment by michinegro** [comment]
Thank you! I'll keep investigating that, I think it would be easier to set discharge instead of velocities.
